# Generated by Django 2.2.3 on 2019-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('clock_type', models.PositiveSmallIntegerField(choices=[(8, '8-hours'), (6, '6-hours'), (4, '4-hours')])),
                ('compleation', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(max_length=200)),
                ('related_clock', models.ManyToManyField(to='clocks.Clock')),
            ],
        ),
    ]
