# Generated by Django 2.2.3 on 2019-07-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='related_clock',
            field=models.ManyToManyField(default=None, to='clocks.Clock'),
        ),
    ]
