# Generated by Django 2.2.3 on 2019-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0002_auto_20190729_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='related_clock',
            field=models.ManyToManyField(blank=True, to='clocks.Clock'),
        ),
    ]
