# Generated by Django 2.2.3 on 2019-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0003_auto_20190729_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='related_clock',
            new_name='following_clock',
        ),
        migrations.AlterField(
            model_name='clock',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='clock',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
