# Generated by Django 2.2.3 on 2019-08-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0004_auto_20190729_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='name',
            new_name='title',
        ),
    ]
