# Generated by Django 2.2.3 on 2019-09-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0006_auto_20190901_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('insight', 'Insight'), ('prowess', 'Prowess'), ('resolve', 'Resolve')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='clock',
            name='clock_type',
            field=models.CharField(choices=[('project', 'Projects Clock'), ('campain', 'Campain Clock'), ('heal', 'Healing Clock'), ('faction', 'Faction Clock'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clock_length',
            field=models.PositiveSmallIntegerField(choices=[(8, '8-hours'), (6, '6-hours'), (4, '4-hours')], default=4),
        ),
        migrations.AlterField(
            model_name='clock',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='clock',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook', models.CharField(choices=[('cutter', 'Cutter'), ('hound', 'Hound'), ('leech', 'Leech'), ('lurk', 'Lurk'), ('slide', 'Slide'), ('spider', 'Spider'), ('whisper', 'Whisper'), ('ghost', 'Ghost'), ('vampire', 'Vampire'), ('hull', 'Hull')], max_length=10)),
                ('heritage', models.CharField(choices=[('ako', 'Akoros'), ('dag', 'Dagger Isles'), ('irv', 'Iruvia'), ('sev', 'Severos'), ('sko', 'Skovlan'), ('tyc', 'Tycheros')], max_length=3)),
                ('background', models.CharField(choices=[('aca', 'Academic'), ('lab', 'Labor'), ('law', 'Law'), ('tra', 'Trade'), ('mil', 'Military'), ('nob', 'Noble'), ('und', 'Underworld')], max_length=3)),
                ('vice', models.CharField(choices=[('fai', 'Faith'), ('gam', 'Gambling'), ('obl', 'Obligation'), ('ple', 'Pleasure'), ('stu', 'Stupor'), ('wei', 'Weird')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('look', models.TextField(max_length=600)),
                ('coins', models.PositiveSmallIntegerField(default=0)),
                ('cold', models.BooleanField(default=False)),
                ('haunted', models.BooleanField(default=False)),
                ('obsessed', models.BooleanField(default=False)),
                ('paranoid', models.BooleanField(default=False)),
                ('reckless', models.BooleanField(default=False)),
                ('soft', models.BooleanField(default=False)),
                ('unstable', models.BooleanField(default=False)),
                ('vicious', models.BooleanField(default=False)),
                ('armor_light', models.BooleanField(default=False)),
                ('armor_heavy', models.BooleanField(default=False)),
                ('armor_special', models.BooleanField(default=False)),
                ('harm_1_1', models.CharField(max_length=300)),
                ('harm_1_2', models.CharField(max_length=300)),
                ('harm_2_1', models.CharField(max_length=300)),
                ('harm_2_2', models.CharField(max_length=300)),
                ('harm_3', models.CharField(max_length=300)),
                ('friend', models.TextField(max_length=300)),
                ('foe', models.TextField(max_length=300)),
                ('abilities', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clocks.Ability')),
                ('action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clocks.Action')),
                ('healing_clock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clocks.Clock')),
                ('notes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clocks.Note')),
            ],
        ),
    ]
